name: Deploy Hexo Blog

env:
  HEXO_STRICT: "false"

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Hexo CLI globally
        run: npm install -g hexo-cli

      - name: Check Hexo version
        run: hexo -v

      - name: Install dependencies
        run: npm install

      - name: Install additional plugins
        run: |
          npm i hexo-renderer-multi-markdown-it --save
          npm i hexo-autoprefixer --save
          npm i hexo-algolia --save
          npm i hexo-algoliasearch --save
          npm i hexo-symbols-count-time --save
          npm i hexo-feed --save

      - name: Check Node.js and npm versions
        run: |
          echo "Node version: $(node -v)"
          echo "npm version: $(npm -v)"

      - name: Output pipeline version
        run: echo "Pipeline version: ${{ github.run_number }}"

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Replace repository URL in config
        run: |
          sed -i "s~git@github.com:~https://${{ secrets.GH_TOKEN }}@github.com/~" _config.yml

      - name: Clean previous build
        run: npx hexo clean

      - name: Generate static files
        run: npx hexo generate

      - name: Deploy Hexo blog
        run: npx hexo deploy    